import type { DomainParamConfig } from "./types.js";

export const DEFAULT_TRACKING_PARAMS = [
  "utm_source",
  "utm_medium",
  "utm_campaign",
  "utm_term",
  "utm_content",
  "utm_id",
  "utm_cid",
  "utm_reader",
  "utm_referrer",
  "utm_name",
  "utm_social",
  "utm_social-type",
  "fbclid",
  "gclid",
  "dclid",
  "twclid",
  "msclkid",
  "mc_cid",
  "mc_eid",
  "pk_campaign",
  "pk_kwd",
  "pk_source",
  "pk_medium",
  "piwik_campaign",
  "piwik_kwd",
  "affiliate",
  "ref",
  "referrer",
  "source",
  "spm",
  "partner",
  "promo",
  "campaign",
  "ad",
  "agid",
  "kwid",
  "adid",
  "cid",
  "sid",
  "pid",
  "aid",
  "bid",
  "vid",
  "__readwiseLocation",
  "isFreemail",
  "triedRedirect",
] as const;

// Params too generic to remove globally, so they are scoped to specific domains
export const DEFAULT_DOMAIN_PARAMS: DomainParamConfig[] = [
  { domains: ["x.com", "twitter.com"], params: ["s", "t"] },
  { domains: ["substack.com"], params: ["publication_id", "post_id", "r"] },
  { domains: ["instagram.com"], params: ["igsh", "igshid", "img_index"] },
];
