name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run tests
      run: pnpm test

    - name: Build extension
      run: pnpm build

    - name: Create release package
      run: |
        mkdir -p release
        zip -r release/sniplink-${{ github.ref_name }}.zip \
          manifest.json \
          icons/ \
          src/*.js \
          src/*.html \
          src/*.css \
          src/icons/ \
          -x "src/test/*" \
          -x "src/*.ts" \
          -x "src/*.map"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: release/sniplink-${{ github.ref_name }}.zip
        generate_release_notes: true
        body: |
          ## Installation
          
          1. Download `sniplink-${{ github.ref_name }}.zip` from the assets below
          2. Extract the ZIP file
          3. Open Chrome and go to `chrome://extensions/`
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
          
          ## What's Changed
          
          See the auto-generated release notes below for changes in this version.